spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.138.130:3306/cloud_sell?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
